import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Brain, AlertCircle } from 'lucide-react';
import { PageTransition } from '../components/PageTransition';
import { SectionHeader } from '../components/SectionHeader';
import { PredictionForm } from '../components/PredictionForm';
import { PredictionResult } from '../components/PredictionResult';
import { predictClaimFraud } from '../services/apiService';

export const Predict = () => {
  const [isLoading, setIsLoading] = useState(false);
  const [loadingStep, setLoadingStep] = useState(0);
  const [predictionResult, setPredictionResult] = useState(null);
  const [errorMessage, setErrorMessage] = useState(null);

  const loadingSteps = [
    'Validating & Normalizing Feature Inputs...',
    'Performing Date & Categorical Encoding...',
    'Applying Saved StandardScaler Transformation...',
    'Executing Random Forest Inference Pipeline...',
    'Generating Factor Explanations & Risk Assessment...'
  ];

  // FIX FOR SPA SCROLL BUG: Ensure page resets to top whenever result changes or resets
  useEffect(() => {
    window.scrollTo({
      top: 0,
      left: 0,
      behavior: 'instant'
    });
  }, [predictionResult]);

  const handleFormSubmit = async (formData) => {
    setIsLoading(true);
    setLoadingStep(0);
    setErrorMessage(null);

    const stepInterval = setInterval(() => {
      setLoadingStep((prev) => (prev < loadingSteps.length - 1 ? prev + 1 : prev));
    }, 180);

    try {
      const result = await predictClaimFraud(formData);
      clearInterval(stepInterval);
      setPredictionResult(result);
    } catch (err) {
      clearInterval(stepInterval);
      console.error('Prediction calculation error:', err);
      setErrorMessage(err.message || 'Unable to analyze this claim. Please check the entered information and try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleReset = () => {
    setPredictionResult(null);
    setErrorMessage(null);
  };

  return (
    <PageTransition>
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10 md:py-16 space-y-10">
        
        {/* Header */}
        <SectionHeader
          badgeText="Supervised ML Random Forest Inference"
          title={predictionResult ? "Claim Fraud Risk Assessment Result" : "Vehicle Insurance Claim Risk Evaluator"}
          subtitle={
            predictionResult
              ? "Actual Machine Learning prediction generated by vehicle_fraud_random_forest.pkl."
              : "Enter vehicle insurance claim attributes, driver demographics, and financial parameters to evaluate risk in real time."
          }
        />

        {/* Error Alert */}
        {errorMessage && (
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            className="p-4 rounded-xl bg-red-500/10 border border-red-500/30 text-red-400 text-sm flex items-center gap-3 shadow-lg"
          >
            <AlertCircle className="w-5 h-5 shrink-0 text-red-400" />
            <div className="flex-1">
              <span className="font-bold">Error: </span>
              <span>{errorMessage}</span>
            </div>
          </motion.div>
        )}

        {/* Dynamic Display: Loading vs Form vs Result */}
        {isLoading ? (
          <motion.div
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            className="p-10 sm:p-16 rounded-2xl bg-[#1A1A1A] border border-[#343434] text-center space-y-6 max-w-xl mx-auto shadow-2xl"
          >
            <div className="relative w-20 h-20 mx-auto flex items-center justify-center">
              <div className="absolute inset-0 rounded-full border-4 border-[#00C878]/20 animate-ping pointer-events-none" />
              <div className="w-16 h-16 rounded-2xl bg-[#00C878]/10 border border-[#00C878]/40 flex items-center justify-center text-[#00C878] shadow-lg shadow-[#00C878]/15">
                <Brain className="w-8 h-8 animate-pulse" />
              </div>
            </div>

            <div className="space-y-2">
              <h3 className="text-xl font-bold font-heading text-[#F5F5F5]">
                Random Forest Model Evaluating Claim...
              </h3>
              <p className="text-xs sm:text-sm text-[#00C878] font-semibold h-6 transition-all">
                {loadingSteps[loadingStep]}
              </p>
            </div>

            {/* Progress bar */}
            <div className="w-full h-1.5 bg-[#141414] rounded-full overflow-hidden border border-[#343434]/80">
              <motion.div 
                className="h-full bg-gradient-to-r from-[#00C878] to-[#8BEF4A] rounded-full"
                animate={{ width: `${((loadingStep + 1) / loadingSteps.length) * 100}%` }}
                transition={{ duration: 0.25 }}
              />
            </div>
          </motion.div>
        ) : !predictionResult ? (
          <PredictionForm onSubmit={handleFormSubmit} isLoading={isLoading} />
        ) : (
          <PredictionResult result={predictionResult} onReset={handleReset} />
        )}

      </div>
    </PageTransition>
  );
};

export default Predict;
